# Default compiler and compiler flags
CC := gcc
CF := -Wall
# If Cross Compiler provided as argument
ifdef CROSS_COMPILE
	CC := $(CROSS_COMPILE)gcc
endif
# Executable
OUTPUT := aesdsocket

# Default Target
$(OUTPUT): aesdsocket.o
	$(CC) $(CF) aesdsocket.o -o $(OUTPUT)
aesdsocket.o: aesdsocket.c
	$(CC) $(CF) -c aesdsocket.c

all: $(OUTPUT)

clean:
	rm -f *.o $(OUTPUT)